# Generated by Django 2.1 on 2018-09-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=20)),
                ('b_pubdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=20)),
                ('h_gender', models.BooleanField()),
                ('h_content', models.CharField(max_length=100)),
                ('h_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_book.BookInfo')),
            ],
        ),
    ]
