# Generated by Django 2.1 on 2018-09-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('aPArea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Area')),
            ],
        ),
    ]
