# Generated by Django 2.1 on 2018-09-07 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='aPArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Area'),
        ),
    ]
